
services:

  # 🔹 Base de datos de usuarios
  db-user:
    image: juanhoyos329/mysql-automarketuao:v1
    container_name: db_user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersautomarketuao
    ports:
      - "3306:3306"
    networks:
      - automarketuao

  # 🔹 Servicio de usuarios
  user-service:
    build:
      context: ./User
      dockerfile: Dockerfile
    container_name: user_service
    ports:      
      - "8081:8081"
    depends_on:
      - db-user
    networks:
      - automarketuao

# 🔹 Base de datos de publicaciones
  db-publicaciones:
    image: miguel491/publicaciones-db:latest
    container_name: publicaciones_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: annie
      MYSQL_DATABASE: AutoMarketUao
    ports:
      - "3307:3306"
    volumes:
      - publicaciones_data:/var/lib/mysql
    networks:
      - automarketuao

# 🔹 Servicio de publicaciones
  publicaciones-service:
    image: miguel491/publicaciones-service:latest
    container_name: publicaciones_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-publicaciones:3306/AutoMarketUao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: annie
    depends_on:
      - db-publicaciones
    restart: on-failure
    networks:
      - automarketuao

    # 🔹 Base de datos de trámites
  db-tramites:
    image: miguel491/mysql-tramites:latest
    container_name: db_tramites
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backtramites
    ports:
      - "3308:3306"
    volumes:
      - mysql-data-tramites:/var/lib/mysql
    networks:
      - automarketuao

  # 🔹 Servicio de trámites
  tramites-service:
    image: miguel491/tramites:latest
    container_name: tramites_service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: db-tramites
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: backtramites
    depends_on:
      - db-tramites
    networks:
      - automarketuao

volumes:
  publicaciones_data:
  mysql-data:
  mysql-data-tramites:

networks:
  automarketuao:
    driver: bridge
